#!/usr/bin/env node
/*
 * resumeVibing-gen.js
 * ---------------------------------------------------------------------------
 * Claude Code SessionStart hook. On every session start it drops a
 * "resume the vibe" launcher into the project's working directory so that,
 * after a reboot or a closed terminal, you can re-orient and jump straight
 * back into the exact Claude Code session you were in.
 *
 *   - Windows  -> writes  resumeVibing.ps1
 *   - Linux/mac-> writes  resumeVibing.sh  (and chmod 0755)
 *
 * It also always (re)writes a small `.resume-session` file holding the current
 * session GUID, so even a hand-customized launcher can pick up the latest id.
 *
 * Safety: a launcher this script generated carries a RESUME_VIBING_AUTOGEN
 * marker. If you edit the launcher and remove that marker, the hook will stop
 * overwriting it (it will still refresh .resume-session).
 *
 * Wire it up in ~/.claude/settings.json:
 *   "hooks": { "SessionStart": [ { "hooks": [
 *     { "type": "command", "command": "node \"<abs path>/resumeVibing-gen.js\"" }
 *   ] } ] }
 */
'use strict';

const fs = require('fs');
const path = require('path');
const os = require('os');

const MARKER = 'RESUME_VIBING_AUTOGEN';

function readStdin() {
  try {
    return fs.readFileSync(0, 'utf8');
  } catch (_) {
    return '';
  }
}

function main() {
  let input = {};
  const raw = readStdin();
  if (raw && raw.trim()) {
    try { input = JSON.parse(raw); } catch (_) { input = {}; }
  }

  const sessionId = String(input.session_id || process.env.CLAUDE_SESSION_ID || '').trim();
  const cwd = String(input.cwd || process.cwd() || '').trim();

  // Nothing useful to write without a target dir.
  if (!cwd) return;

  // Don't litter the home directory itself; only real project folders.
  try {
    if (path.resolve(cwd) === path.resolve(os.homedir())) return;
  } catch (_) { /* ignore */ }

  let projectName = path.basename(cwd) || 'project';
  projectName = projectName.replace(/['\r\n]/g, ''); // keep it safe to embed

  // Always refresh the session-id sidecar file (the one dynamic bit).
  if (sessionId) {
    try { fs.writeFileSync(path.join(cwd, '.resume-session'), sessionId + '\n', 'utf8'); }
    catch (_) { /* best effort */ }
  }

  const isWindows = process.platform === 'win32';
  const fileName = isWindows ? 'resumeVibing.ps1' : 'resumeVibing.sh';
  const target = path.join(cwd, fileName);

  // Respect hand-customized launchers: if the file exists but no longer carries
  // our marker, leave it alone (we already refreshed .resume-session above).
  if (fs.existsSync(target)) {
    let existing = '';
    try { existing = fs.readFileSync(target, 'utf8'); } catch (_) { existing = ''; }
    if (existing && existing.indexOf(MARKER) === -1) return;
  }

  const body = isWindows
    ? renderPs1(projectName, sessionId)
    : renderSh(projectName, sessionId);

  try {
    fs.writeFileSync(target, body, 'utf8');
    if (!isWindows) fs.chmodSync(target, 0o755);
  } catch (_) { /* best effort, never break the session */ }
}

function renderPs1(project, guid) {
  const gid = guid || '';
  return `#requires -Version 5.1
<#
    resumeVibing.ps1 - one-shot "where was I" + resume for: ${project}

    Prints git state and recent files, then drops you back into the Claude
    Code session you were last in.

    Resume session GUID: ${gid || '(none captured yet - see .resume-session)'}

    Usage:
        powershell -ExecutionPolicy Bypass -File .\\resumeVibing.ps1            # orient + resume (normal prompts)
        powershell -ExecutionPolicy Bypass -File .\\resumeVibing.ps1 -JustDoIt  # resume, skip permission prompts
        powershell -ExecutionPolicy Bypass -File .\\resumeVibing.ps1 -NoLaunch  # just orient, do not launch

    Auto-generated by resumeVibing-gen.js (Claude Code SessionStart hook).
    Safe to edit. To stop the hook from overwriting your edits, delete the
    ${MARKER} marker line below.
    ${MARKER}
#>
[CmdletBinding()]
param(
    [string]$SessionId,
    [switch]$JustDoIt,
    [switch]$NoLaunch
)

$ProjectDir = $PSScriptRoot
Set-Location $ProjectDir

# Resolve the session id: -SessionId > embedded default > env > .resume-session file.
$DefaultSessionId = '${gid}'
if (-not $SessionId) { $SessionId = $DefaultSessionId }
if (-not $SessionId) { $SessionId = $env:CLAUDE_RESUME_SESSION }
if (-not $SessionId) {
    $sessionFile = Join-Path $ProjectDir '.resume-session'
    if (Test-Path $sessionFile) { $SessionId = (Get-Content $sessionFile -Raw).Trim() }
}

Write-Host ''
Write-Host '================ ${project} - resume ================' -ForegroundColor Cyan
Write-Host "Project: $ProjectDir"
Write-Host ''

if (Get-Command git -ErrorAction SilentlyContinue) {
    if (Test-Path (Join-Path $ProjectDir '.git')) {
        Write-Host '--- Git ---' -ForegroundColor Yellow
        Write-Host "Branch:      $(git rev-parse --abbrev-ref HEAD 2>$null)"
        Write-Host "Last commit: $(git log --oneline -1 2>$null)"
        Write-Host "Remote:      $(git remote get-url origin 2>$null)"
        Write-Host 'Working tree:'
        $status = git status --short
        if ($status) { $status | ForEach-Object { "  $_" } } else { Write-Host '  clean' -ForegroundColor Green }
        Write-Host ''
    }
}

Write-Host '--- Files (most recently changed) ---' -ForegroundColor Yellow
Get-ChildItem -File | Sort-Object LastWriteTime -Descending |
    Select-Object -First 12 Name, Length, LastWriteTime | Format-Table -Auto
Write-Host '=====================================================' -ForegroundColor Cyan
Write-Host ''

if (-not $SessionId) {
    Write-Warning 'No session id found. Pass -SessionId, set $env:CLAUDE_RESUME_SESSION, or add a .resume-session file.'
    return
}

$manualCmd = "claude --resume $SessionId" + $(if ($JustDoIt) { ' --dangerously-skip-permissions' } else { '' })

if ($NoLaunch) {
    Write-Host 'Skipping launch (-NoLaunch). To resume manually:' -ForegroundColor DarkGray
    Write-Host "  $manualCmd" -ForegroundColor DarkGray
    return
}

if (-not (Get-Command claude -ErrorAction SilentlyContinue)) {
    Write-Warning "'claude' not found on PATH. Resume manually with:"
    Write-Host "  $manualCmd"
    return
}

$claudeArgs = @('--resume', $SessionId)
if ($JustDoIt) {
    $claudeArgs += '--dangerously-skip-permissions'
    Write-Host 'Resuming Claude WITHOUT permission prompts (-JustDoIt).' -ForegroundColor Yellow
} else {
    Write-Host 'Resuming Claude (normal permission prompts). Add -JustDoIt to skip them.' -ForegroundColor Green
}
Write-Host "  $manualCmd" -ForegroundColor DarkGray
Write-Host ''

claude @claudeArgs
`;
}

function renderSh(project, guid) {
  const gid = guid || '';
  return `#!/usr/bin/env bash
# resumeVibing.sh - one-shot "where was I" + resume for: ${project}
#
# Prints git state and recent files, then drops you back into the Claude Code
# session you were last in.
#
# Resume session GUID: ${gid || '(none captured yet - see .resume-session)'}
#
# Usage:
#   ./resumeVibing.sh               # orient + resume (normal prompts)
#   ./resumeVibing.sh --just-do-it  # resume, skip permission prompts
#   ./resumeVibing.sh --no-launch   # just orient, do not launch
#
# Auto-generated by resumeVibing-gen.js (Claude Code SessionStart hook).
# Safe to edit. To stop the hook from overwriting your edits, delete the
# ${MARKER} marker line below.
# ${MARKER}
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
cd "$PROJECT_DIR"

JUST_DO_IT=0
NO_LAUNCH=0
SESSION_ID=""
for arg in "$@"; do
  case "$arg" in
    --just-do-it|-y) JUST_DO_IT=1 ;;
    --no-launch|-n)  NO_LAUNCH=1 ;;
    *)               SESSION_ID="$arg" ;;
  esac
done

# Resolve session id: arg > embedded default > env > .resume-session file.
DEFAULT_SESSION_ID="${gid}"
[ -z "$SESSION_ID" ] && SESSION_ID="$DEFAULT_SESSION_ID"
[ -z "$SESSION_ID" ] && SESSION_ID="\${CLAUDE_RESUME_SESSION:-}"
if [ -z "$SESSION_ID" ] && [ -f "$PROJECT_DIR/.resume-session" ]; then
  SESSION_ID="$(tr -d '[:space:]' < "$PROJECT_DIR/.resume-session")"
fi

echo ""
echo "================ ${project} - resume ================"
echo "Project: $PROJECT_DIR"
echo ""

if command -v git >/dev/null 2>&1 && [ -d "$PROJECT_DIR/.git" ]; then
  echo "--- Git ---"
  echo "Branch:      $(git rev-parse --abbrev-ref HEAD 2>/dev/null || true)"
  echo "Last commit: $(git log --oneline -1 2>/dev/null || true)"
  echo "Remote:      $(git remote get-url origin 2>/dev/null || true)"
  echo "Working tree:"
  if [ -n "$(git status --short)" ]; then git status --short | sed 's/^/  /'; else echo "  clean"; fi
  echo ""
fi

echo "--- Files (most recently changed) ---"
ls -lt 2>/dev/null | head -n 13
echo "====================================================="
echo ""

if [ -z "$SESSION_ID" ]; then
  echo "WARN: no session id found. Pass it as an arg, set CLAUDE_RESUME_SESSION, or add a .resume-session file." >&2
  exit 0
fi

MANUAL_CMD="claude --resume $SESSION_ID"
[ "$JUST_DO_IT" -eq 1 ] && MANUAL_CMD="$MANUAL_CMD --dangerously-skip-permissions"

if [ "$NO_LAUNCH" -eq 1 ]; then
  echo "Skipping launch (--no-launch). To resume manually:"
  echo "  $MANUAL_CMD"
  exit 0
fi

if ! command -v claude >/dev/null 2>&1; then
  echo "WARN: 'claude' not found on PATH. Resume manually with:" >&2
  echo "  $MANUAL_CMD"
  exit 0
fi

if [ "$JUST_DO_IT" -eq 1 ]; then
  echo "Resuming Claude WITHOUT permission prompts (--just-do-it)."
  echo "  $MANUAL_CMD"
  echo ""
  exec claude --resume "$SESSION_ID" --dangerously-skip-permissions
else
  echo "Resuming Claude (normal permission prompts). Add --just-do-it to skip them."
  echo "  $MANUAL_CMD"
  echo ""
  exec claude --resume "$SESSION_ID"
fi
`;
}

main();
